version: "3.8"

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: bgpdf-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - bgpdf-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bgpdf-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION_NAME=pdf_chunks
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - MAX_FILE_SIZE_MB=20
      - UPLOAD_DIR=./uploads
      - CHUNK_SIZE=500
      - CHUNK_OVERLAP=50
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - TESSERACT_LANG=bul+eng
    depends_on:
      - qdrant
    networks:
      - bgpdf-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bgpdf-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - bgpdf-network
    restart: unless-stopped

volumes:
  qdrant_storage:

networks:
  bgpdf-network:
    driver: bridge
